"""Add API keys and enhancements

Revision ID: 9ce9de73688d
Revises: 309e4d3e0ac2
Create Date: 2025-10-23 11:41:55.939002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce9de73688d'
down_revision: Union[str, None] = '309e4d3e0ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
